title: Ahmed’s Newsletter
author: Ahmed Elkollaly
description: Platform engineering, reliability, and growth.
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
substack_url: https://ahmedelkolaly.substack.com